using Terminal.Gui.Reflect.Services;

namespace Terminal.Gui.Reflect.Interfaces;

public interface IIconService
{
    IconTier        Tier                  { get; set; }
    char            ArrowLeft             { get; }
    char            ArrowRight            { get; }
    char            ArrowUp               { get; }
    char            ArrowDown             { get; }
    char            ArrowLeftRight        { get; }
    char            ArrowUpDown           { get; }
    char            ArrowUpDownBase       { get; }
    char            ArrowLeftFilled       { get; }
    char            ArrowRightFilled      { get; }
    char            ArrowUpFilled         { get; }
    char            ArrowDownFilled       { get; }
    char            ArrowLeftSmall        { get; }
    char            ArrowRightSmall       { get; }
    char            ArrowUpSmall          { get; }
    char            ArrowDownSmall        { get; }
    char            ArrowLeftOutline      { get; }
    char            ArrowRightOutline     { get; }
    char            ArrowUpOutline        { get; }
    char            ArrowDownOutline      { get; }
    char            ArrowDoubleLeft       { get; }
    char            ArrowDoubleRight      { get; }
    char            ArrowDoubleUp         { get; }
    char            ArrowDoubleDown       { get; }
    char            ArrowNorthEast        { get; }
    char            ArrowNorthWest        { get; }
    char            ArrowSouthEast        { get; }
    char            ArrowSouthWest        { get; }
    char            ArrowUndo             { get; }
    char            ArrowRedo             { get; }
    char            ArrowRefresh          { get; }
    char            BoxHorizontal         { get; }
    char            BoxVertical           { get; }
    char            BoxTopLeft            { get; }
    char            BoxTopRight           { get; }
    char            BoxBottomLeft         { get; }
    char            BoxBottomRight        { get; }
    char            BoxCross              { get; }
    char            BoxTeeLeft            { get; }
    char            BoxTeeRight           { get; }
    char            BoxTeeTop             { get; }
    char            BoxTeeBottom          { get; }
    char            BoxDoubleHorizontal   { get; }
    char            BoxDoubleVertical     { get; }
    char            BoxDoubleTopLeft      { get; }
    char            BoxDoubleTopRight     { get; }
    char            BoxDoubleBottomLeft   { get; }
    char            BoxDoubleBottomRight  { get; }
    char            BoxDoubleCross        { get; }
    char            BoxDoubleTeeLeft      { get; }
    char            BoxDoubleTeeRight     { get; }
    char            BoxDoubleTeeTop       { get; }
    char            BoxDoubleTeeBottom    { get; }
    char            BoxHeavyHorizontal    { get; }
    char            BoxHeavyVertical      { get; }
    char            BoxHeavyTopLeft       { get; }
    char            BoxHeavyTopRight      { get; }
    char            BoxHeavyBottomLeft    { get; }
    char            BoxHeavyBottomRight   { get; }
    char            BoxHeavyCross         { get; }
    char            BoxHeavyTeeLeft       { get; }
    char            BoxHeavyTeeRight      { get; }
    char            BoxHeavyTeeTop        { get; }
    char            BoxHeavyTeeBottom     { get; }
    char            BoxRoundedTopLeft     { get; }
    char            BoxRoundedTopRight    { get; }
    char            BoxRoundedBottomLeft  { get; }
    char            BoxRoundedBottomRight { get; }
    char            BoxDashHorizontal2    { get; }
    char            BoxDashHorizontal3    { get; }
    char            BoxDashHorizontal4    { get; }
    char            BoxDashVertical2      { get; }
    char            BoxDashVertical3      { get; }
    char            BoxDashVertical4      { get; }
    char            BlockFull             { get; }
    char            BlockLight            { get; }
    char            BlockMedium           { get; }
    char            BlockDark             { get; }
    char            BlockTop              { get; }
    char            BlockBottom           { get; }
    char            BlockLeft             { get; }
    char            BlockRight            { get; }
    char            BlockUpperLeft        { get; }
    char            BlockUpperRight       { get; }
    char            BlockLowerLeft        { get; }
    char            BlockLowerRight       { get; }
    char            BlockEighth1          { get; }
    char            BlockEighth2          { get; }
    char            BlockEighth3          { get; }
    char            BlockEighth4          { get; }
    char            BlockEighth5          { get; }
    char            BlockEighth6          { get; }
    char            BlockEighth7          { get; }
    char            BlockTopLine          { get; }
    char            BlockRightLine        { get; }
    char            SquareFilled          { get; }
    char            SquareOutline         { get; }
    char            SquareSmallFilled     { get; }
    char            SquareSmallOutline    { get; }
    char            RectangleHorizontal   { get; }
    char            RectangleVertical     { get; }
    char            TriangleUpFilled      { get; }
    char            TriangleUpOutline     { get; }
    char            TriangleDownFilled    { get; }
    char            TriangleDownOutline   { get; }
    char            TriangleRightFilled   { get; }
    char            TriangleRightOutline  { get; }
    char            TriangleLeftFilled    { get; }
    char            TriangleLeftOutline   { get; }
    char            TriangleUpSmall       { get; }
    char            TriangleDownSmall     { get; }
    char            TriangleRightSmall    { get; }
    char            TriangleLeftSmall     { get; }
    char            DiamondFilled         { get; }
    char            DiamondOutline        { get; }
    char            DiamondSmall          { get; }
    char            CircleFilled          { get; }
    char            CircleOutline         { get; }
    char            CircleBullseye        { get; }
    char            CircleInverse         { get; }
    char            CircleDotted          { get; }
    char            Lozenge               { get; }
    char            LozengeOutline        { get; }
    char            Bullet                { get; }
    char            BulletOutline         { get; }
    char            Ellipsis              { get; }
    char            MiddleDot             { get; }
    char            Dash                  { get; }
    char            HorizontalBar         { get; }
    char            VerticalEllipsis      { get; }
    char            Star                  { get; }
    char            StarOutline           { get; }
    char            Heart                 { get; }
    char            HeartOutline          { get; }
    char            Diamond               { get; }
    char            Club                  { get; }
    char            Spade                 { get; }
    char            Note                  { get; }
    char            Notes                 { get; }
    char            Female                { get; }
    char            Male                  { get; }
    char            SmileyFilled          { get; }
    char            SmileyOutline         { get; }
    char            Sun                   { get; }
    char            Moon                  { get; }
    char            Check                 { get; }
    char            CheckBold             { get; }
    char            Cross                 { get; }
    char            CrossDiagonal         { get; }
    char            Plus                  { get; }
    char            Minus                 { get; }
    char            PlusMinus             { get; }
    char            Multiply              { get; }
    char            Divide                { get; }
    char            Infinity              { get; }
    char            Degree                { get; }
    char            Paragraph             { get; }
    char            Section               { get; }
    char            Copyright             { get; }
    char            Registered            { get; }
    char            Trademark             { get; }
    char            Sigma                 { get; }
    char            Pi                    { get; }
    char            Omega                 { get; }
    char            Micro                 { get; }
    char            AngleLeft             { get; }
    char            AngleRight            { get; }
    char            Superscript2          { get; }
    char            Superscript3          { get; }
    char            DoubleExclamation     { get; }
    char            Intersection          { get; }
    char            ApproxEqual           { get; }
    char            LessEqual             { get; }
    char            GreaterEqual          { get; }
    char            NotEqual              { get; }
    char            RightAngle            { get; }
    char            Play                  { get; }
    char            Pause                 { get; }
    char            Stop                  { get; }
    char            Eject                 { get; }
    char            SkipBack              { get; }
    char            SkipForward           { get; }
    char            Rewind                { get; }
    char            FastForward           { get; }
    char            Add                   { get; }
    char            Remove                { get; }
    char            Edit                  { get; }
    char            Delete                { get; }
    char            Save                  { get; }
    char            Copy                  { get; }
    char            Paste                 { get; }
    char            Cut                   { get; }
    char            Expand                { get; }
    char            Collapse              { get; }
    char            Sort                  { get; }
    char            Filter                { get; }
    char            Menu                  { get; }
    char            Grid                  { get; }
    char            List                  { get; }
    char            Help                  { get; }
    char            Error                 { get; }
    char            Success               { get; }
    char            Warning               { get; }
    char            Information           { get; }
    char            Pending               { get; }
    char            Running               { get; }
    char            Spinner               { get; }
    char            House                 { get; }
    char            Telephone             { get; }
    char            Envelope              { get; }
    char            Pencil                { get; }
    char            Scissors              { get; }
    char            Hourglass             { get; }
    char            Watch                 { get; }
    char            Anchor                { get; }
    char            Flag                  { get; }
    char            Skull                 { get; }
    char            Recycling             { get; }
    char            Power                 { get; }
    char            Gear                  { get; }
    char            Lock                  { get; }
    char            Key                   { get; }
    char            File                  { get; }
    char            Folder                { get; }
    char            Magnifier             { get; }
    char            Bell                  { get; }
    char            BellSlash             { get; }
    char            Wrench                { get; }
    char            Hammer                { get; }
    char            Pin                   { get; }
    char            Tag                   { get; }
    char            Bookmark              { get; }
    char            Trophy                { get; }
    char            Target                { get; }
    char            Link                  { get; }
    char            Globe                 { get; }
    char            Cloud                 { get; }
    char            Snowflake             { get; }
    char            Lightning             { get; }
    char            Umbrella              { get; }
    char            Person                { get; }
    char            Eye                   { get; }
    char            Download              { get; }
    char            Upload                { get; }
    char            TreeBranch            { get; }
    char            TreeNodeLast          { get; }
    char            TreeNodeExpanded      { get; }
    char            TreeNodeCollapsed     { get; }
    char            TreeIndent            { get; }
}